version: '3.9'
services:
  db:
    restart: 'always'
    build: './pocketbase'
    expose:
      - 80
    ports:
      - ${PORTDB:-8081}:80
    environment:
      FRONTEND_URL: http://web:3001
    volumes:
      - dbdata:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_hooks:/pb/pb_hooks
    networks:
      - nginx-network
  web:
    restart: 'always'
    build: 
      context: './web'
      dockerfile: 'Dockerfile'
      args:
        PUBLIC_DATABASE: ${PUBLIC_DATABASE:-https://api.cc-web.cloud/zerzinator}
    ports:
      - ${PORTWEB:-8080}:3001
    expose:
      - 3001
    environment:
      NODE_ENV: production
      PORT: 3001
      PUBLIC_DATABASE: ${PUBLIC_DATABASE:-https://api.cc-web.cloud/zerzinator}
      # ORIGIN: https://zerzinator.cc-web.cloud
    networks:
      - nginx-network

volumes:
  dbdata:

networks:
  nginx-network:
    name: nginx-proxy-manager_default
    external: true