name: deploy ⬆️

on: workflow_dispatch

jobs:

  build:
    name: Build ⚒️
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Stop running containers
      run: docker-compose down
    - name: Build the app
      run: docker-compose up --build -d